[package]
name = "balancer"
version = "1.0.0"
edition = "2021"

[profile.release]
opt-level = 3
strip = true
lto = "fat"
codegen-units = 1
debug = false

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
log = "0.4.25"
mvlogger = "0.4.0"
mvutils = "1.1.7"
rand = "0.9.0"
